language: python

services:
  - docker

before_install:
  - docker build -t minikeyvalue -f Dockerfile .

script:
  - docker run --hostname localhost minikeyvalue bash -c "(./bringup.sh &) && ./test.py && go run thrasher.go lib.go && ./rtest.sh"

